---
title: "Descriptive Statistics"
author: "Ahyoung Cho & Rafeya Raquib"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
# Load packages
library(dplyr)
library(plyr)
library(car)
library(vroom)
library(tidyverse)
library(tidyr)
library(tidyselect)
library(data.table)
library(purrr)
library(knitr)
library(DT)
library(kableExtra)
library(ggplot2)
library(zoo)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
#knitr::opts_knit$set(root.dir ='covid-race-metro')
```

```{r, warning=FALSE, message = FALSE}
clean_data <- function(data) {
  data %>%
    filter(Notes != "Total") %>%
    mutate(AgeGroup = case_when(grepl("_25_54", FileName) ~ "25-54",
                                grepl("_55_74", FileName) ~ "55-74",
                                grepl("_75plus", FileName) ~ "75plus"),
           Race = case_when(grepl("hisp", FileName) ~ "Hispanic",
                                grepl("nhwhite", FileName) ~ "Non-Hispanic White",
                                grepl("nhblack", FileName) ~ "Non-Hispanic Black"),
           Metro = case_when(grepl("large", FileName) ~ "Large Metro",
                            grepl("_medsmall", FileName) ~ "Medium/Small Metro",
                            grepl("_nonmetro", FileName) ~ "Nonmetro"),
           Wave = case_when(Month.Code %in% c("2020/03", "2020/04", 
                                              "2020/05") ~ "Initial", 
                            Month.Code %in% c( "2020/06","2020/07", 
                                               "2020/08") ~ "Second",
                            Month.Code %in% c("2020/09", "2020/10", "2020/11", 
                                              "2020/12", "2021/01", 
                                              "2021/02", "2021/03", 
                                              "2021/04", "2021/05") ~ "Alpha",
                            Month.Code %in% c("2021/06", "2021/07","2021/08", 
                                              "2021/09", "2021/10") ~ "Delta",
                            Month.Code %in% c("2021/11", "2021/12", "2022/01", "2022/02") ~ "Omicron",
                            TRUE ~ Month.Code)) %>%
    dplyr::select(FileName, Metro, Month.Code, Wave, Race, AgeGroup, Deaths) %>%
    mutate(Wave = na_if(Wave, "")) %>%
    na.omit() %>%
    mutate_all(funs(replace(., .=='Suppressed', NA))) %>%
    dplyr::mutate(Deaths = as.integer(Deaths))
}

list_of_files <- list.files(path = "../Data/month_race_metro/", recursive = TRUE,
                            pattern = ".txt", 
                            full.names = TRUE)

df_death <- list_of_files %>%
  purrr::set_names(nm = (basename(.) %>% tools::file_path_sans_ext())) %>%
  purrr::map_df(read.delim, .id = "FileName",  colClasses=c("character")) %>%
  clean_data()
```

```{r}
# Rows with NAs 
nrow(df_death) # 648
summary(df_death$Deaths)
# 3 are NAs
NAs <- subset(df_death, is.na(df_death$Deaths)) 
```

```{r}
# Replace NAs with beta distribution 
set.seed(12345)
df_death$Deaths[is.na(df_death$Deaths)] <- sample(floor((rbeta(nrow(df_death), 2, 3)*10)), sum(is.na(df_death$Deaths)), replace = TRUE) 
```

```{r, warning=FALSE, message = FALSE}
clean_total_data <- function(data) {
  data %>%
    filter(Notes != "Total") %>%
    mutate(AgeGroup = case_when(grepl("_25_54", FileName) ~ "25-54",
                                grepl("_55_74", FileName) ~ "55-74",
                                grepl("_75plus", FileName) ~ "75plus"),
           Race = case_when(grepl("total", FileName) ~ "All"),
           Metro = case_when(grepl("large", FileName) ~ "Large Metro",
                            grepl("_medsmall", FileName) ~ "Medium/Small Metro",
                            grepl("_nonmetro", FileName) ~ "Nonmetro"),
           Wave = case_when(Month.Code %in% c("2020/03", "2020/04", 
                                              "2020/05") ~ "Initial", 
                            Month.Code %in% c( "2020/06","2020/07", 
                                               "2020/08") ~ "Second",
                            Month.Code %in% c("2020/09", "2020/10", "2020/11", 
                                              "2020/12", "2021/01", 
                                              "2021/02", "2021/03", 
                                              "2021/04", "2021/05") ~ "Alpha",
                            Month.Code %in% c("2021/06", "2021/07","2021/08", 
                                              "2021/09", "2021/10") ~ "Delta",
                            Month.Code %in% c("2021/11", "2021/12", "2022/01", "2022/02") ~ "Omicron",
                            TRUE ~ Month.Code)) %>%
    dplyr::select(FileName, Metro, Month.Code, Wave, Race, AgeGroup, Deaths) %>%
    mutate(Wave = na_if(Wave, "")) %>%
    na.omit() %>%
    mutate_all(funs(replace(., .=='Suppressed', NA))) %>%
    dplyr::mutate(Deaths = as.integer(Deaths))
}

list_of_files <- list.files(path = "../Data/month_metro/", recursive = TRUE,
                            pattern = ".txt", 
                            full.names = TRUE)

df_death_total <- list_of_files %>%
  purrr::set_names(nm = (basename(.) %>% tools::file_path_sans_ext())) %>%
  purrr::map_df(read.delim, .id = "FileName",  colClasses=c("character")) %>%
  clean_total_data()
```

```{r}
df_death <- rbind(df_death, df_death_total)

metro_wave_race <- df_death %>% dplyr::group_by(Metro,Wave,Race)%>%
  dplyr::summarise(Deaths=sum(Deaths)) %>% ungroup()

race <- metro_wave_race %>% dplyr::group_by(Race)%>%
  dplyr::summarise(Deaths=sum(Deaths)) %>% ungroup() %>%
  dplyr::add_row(Race="Other",Deaths=sum(metro_wave_race$Deaths[metro_wave_race$Race=="All"])-
                   sum(metro_wave_race$Deaths[metro_wave_race$Race!="All"]))%>%
  dplyr::mutate(Percent=round(Deaths/977018*100,1))

```

```{r}
######################
##IMPORT/CLEAN DATA ##
######################
age <- data.table::fread('../Data/descriptive/age.txt',
  na.strings = c("Missing", "Suppressed", "Not Applicable"),
  keepLeadingZeros = TRUE) %>% 
  dplyr::select(`Single-Year Ages Code`,Deaths) %>%
  dplyr::rename(deaths=Deaths,
         age=`Single-Year Ages Code`) %>% na.omit()

gender <- data.table::fread(
  '../Data/descriptive/gender.txt',
  na.strings = c("Missing", "Suppressed", "Not Applicable"),
  keepLeadingZeros = TRUE) %>% 
  dplyr::select(Gender, Deaths) %>%
  dplyr::rename(deaths=Deaths,
         gender=Gender)

duplicate_index <- rep(1:nrow(age), age$deaths)

long_age <- age[duplicate_index,]

age_avg <- long_age %>% dplyr::summarise(mean=mean(age),
                                         sd=sd(age))
gender_per <- gender %>% dplyr::filter(gender %in% c("Male","Female")) %>% dplyr::mutate(Percent=round(deaths/sum(deaths)*100,1))
```


```{r}
pop_agegroup_metro<- readRDS(file = "../Data/population/pop_agegroup_metro.rds") %>%
  dplyr::filter(AgeGroup!="0-24") %>%
  dplyr::group_by(Metro,Race)%>%
  dplyr::summarise(pop_avg=round(sum(Population)/24,0)) %>%
  ungroup() %>%
  dplyr::group_by(Race)%>%
  dplyr::mutate(tot=sum(pop_avg),
                per=round(pop_avg/sum(pop_avg)*100,1))

```


```{r}
# Clean Non-Hispanic 
clean_nh <- function(data) {
  data %>%
  filter(Single.Race.6 == "American Indian or Alaska Native" | Single.Race.6 == "Asian" | Single.Race.6 == "Black or African American" | Single.Race.6 == "Native Hawaiian or Other Pacific Islander" | Single.Race.6 == "White") %>%
  dplyr::rename(Race = Single.Race.6) %>%
  mutate(Year = case_when(grepl("yr1_", FileName) ~ "Y1",
                           grepl("yr2_", FileName) ~ "Y2"),
         Metro = case_when(grepl("large", FileName) ~ "Large Metro",
                           grepl("_medsmall", FileName) ~ "Medium/Small Metro",
                           grepl("_nonmetro", FileName) ~ "Nonmetro"),
         AgeGroup = case_when(grepl("_25_54", FileName) ~ "25-54",
                           grepl("_55_74", FileName) ~ "55-74",
                           grepl("_75plus", FileName) ~ "75plus",
                           grepl("all", FileName) ~ "All"),
         Race = dplyr::recode(Race, `American Indian or Alaska Native` = "NH AIAN",
                              `Asian` = "NH Asian",
                              `Black or African American` = "NH Black",
                              `Native Hawaiian or Other Pacific Islander` = "NH NHOPI",
                              `White` = "NH White")) %>%
  dplyr::select(FileName, Year, Race, AgeGroup, Deaths, Metro)
}

list_of_files_nh <- list.files(path = "../Data/year_race_metro/", recursive = TRUE,
                            pattern = "([a-zA-Z0-9]*)+_nonhisp+_([a-zA-Z0-9]*).*.txt", 
                            full.names = TRUE)

df_nh <- list_of_files_nh %>%
  purrr::set_names(nm = (basename(.) %>% tools::file_path_sans_ext())) %>%
  purrr::map_df(read.delim, .id = "FileName") %>%
  as.tibble() %>%
  clean_nh()


# Clean Hispanic
clean_hispanic <- function(data) {
  data %>% filter(Notes != "Total") %>%
  mutate(Year = case_when(grepl("yr1_", FileName) ~ "Y1",
                           grepl("yr2_", FileName) ~ "Y2"),
         Race = "Hispanic",
         Metro = case_when(grepl("large", FileName) ~ "Large Metro",
                           grepl("_medsmall", FileName) ~ "Medium/Small Metro",
                           grepl("_nonmetro", FileName) ~ "Nonmetro"),
         AgeGroup = case_when(grepl("_25_54", FileName) ~ "25-54",
                           grepl("_55_74", FileName) ~ "55-74",
                           grepl("_75plus", FileName) ~ "75plus",
                           grepl("all", FileName) ~ "All")) %>%
  dplyr::select(FileName, Year, Race, AgeGroup, Deaths, Metro)
}


list_of_files_hispanic <- list.files(path = "../Data/year_race_metro/", recursive = TRUE,
                            pattern = "([a-zA-Z0-9]*)+_hisp+_([a-zA-Z0-9]*).*.txt", 
                            full.names = TRUE)

df_hispanic <- list_of_files_hispanic %>%
  purrr::set_names(nm = (basename(.) %>% tools::file_path_sans_ext())) %>%
  purrr::map_df(read.delim, .id = "FileName") %>%
  as.tibble() %>%
  clean_hispanic() %>% drop_na(Deaths)

# Metro dataset
df_death <- bind_rows(df_nh, df_hispanic)

year_race <- df_death %>% dplyr::group_by(Year,Race) %>% dplyr::summarise(Deaths=sum(Deaths))
```




